### ISSUE TITLE
Ruby version

### ISSUE THREAD

**Issue by vigneshmanick** [conda-forge/asciidoctor-feedstock#9]
### Comment:

Hello,

Installing the package installs ruby version ` 2.6`. Is there a possiblity to also support ruby version to >=3 ?.  

I initially thought that the downloaded ruby version is due to my OS `RHEL-7.9` , so i tried to 

```bash
conda install ruby
```
and got ruby 3.1.2 installed

```bash
ruby --version
ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux]
```

Inside the `.ci_support` folder i see that there are only yml files for `linux_64_ruby2.5.yaml` and `linux_64_ruby2.6.yaml`,  could you please consider adding ruby 3 too?

Thanks in advance!

**Comment by vigneshmanick** [comment]
@awvwgk , i see that you are set as the maintainer of this package.  Could you please have a look. Thanks!

**Comment by awvwgk** [comment]
Might need to rebuild the package to get a newer Ruby version. But could also be an issue with the global pinning of Ruby in cf. There are unfortunately not many gems packaged on cf so this part of the ecosystem is not very active.

**Comment by vigneshmanick** [comment]
Could you please try rebuilding to see if the new ruby version is then available?. The [ruby feedstock](https://github.com/conda-forge/ruby-feedstock)  has version 3.1.2 available since 10 Months.

If it doesn't work and it's related to Ruby version being pinned by conda forge itself, how could we communicate to the corresponding parties?

Thanks in advance!

**Comment by awvwgk** [comment]
Looks like there is [an migration for Ruby 3.1 started already](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/ruby31.yaml), but since you asked nicely, I'll manually migrate the feedstock (see #10).
